### ISSUE TITLE
Error when deploying to Heroku (Could not open library '/usr/lib/ssl')

### ISSUE THREAD

**Issue by guilhermekfe** [GemHQ/money-tree#18]
I get the following error when I try to deploy a project to heroku with this gem as dependency:

```
2017-06-12T20:03:50.912570+00:00 app[web.1]: * Version 3.9.1 (ruby 2.3.1-p112), codename: Private Caller
2017-06-12T20:03:50.912540+00:00 app[web.1]: Puma starting in single mode...
2017-06-12T20:03:50.912571+00:00 app[web.1]: * Min threads: 5, max threads: 5
2017-06-12T20:03:50.912572+00:00 app[web.1]: * Environment: production
2017-06-12T20:03:52.571169+00:00 app[web.1]: ! Unable to load application: LoadError: Could not open library '/usr/lib/ssl': /usr/lib/ssl: cannot read file data: Is a directory.
2017-06-12T20:03:52.571196+00:00 app[web.1]: Could not open library 'libssl.so': libssl.so: cannot open shared object file: No such file or directory
2017-06-12T20:03:52.571379+00:00 app[web.1]: bundler: failed to load command: puma (/app/vendor/bundle/ruby/2.3.0/bin/puma)
2017-06-12T20:03:52.571474+00:00 app[web.1]: LoadError: Could not open library '/usr/lib/ssl': /usr/lib/ssl: cannot read file data: Is a directory.
2017-06-12T20:03:52.571476+00:00 app[web.1]: Could not open library 'libssl.so': libssl.so: cannot open shared object file: No such file or directory
2017-06-12T20:03:52.571477+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.3.0/gems/ffi-1.9.18/lib/ffi/library.rb:147:in `block in ffi_lib'
2017-06-12T20:03:52.571477+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.3.0/gems/ffi-1.9.18/lib/ffi/library.rb:100:in `map'
2017-06-12T20:03:52.571478+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.3.0/gems/ffi-1.9.18/lib/ffi/library.rb:100:in `ffi_lib'
2017-06-12T20:03:52.571479+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.3.0/gems/money-tree-0.9.0/lib/openssl_extensions.rb:9:in `<module:OpenSSLExtensions>'
2017-06-12T20:03:52.571480+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.3.0/gems/money-tree-0.9.0/lib/openssl_extensions.rb:7:in `<module:MoneyTree>'
2017-06-12T20:03:52.571481+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.3.0/gems/money-tree-0.9.0/lib/openssl_extensions.rb:6:in `<top (required)>'
2017-06-12T20:03:52.571481+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.3.0/gems/money-tree-0.9.0/lib/money-tree.rb:1:in `require'
2017-06-12T20:03:52.571482+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.3.0/gems/money-tree-0.9.0/lib/money-tree.rb:1:in `<top (required)>'
2017-06-12T20:03:52.571483+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.3.0/gems/bundler-1.13.7/lib/bundler/runtime.rb:91:in `require'
2017-06-12T20:03:52.571483+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.3.0/gems/bundler-1.13.7/lib/bundler/runtime.rb:91:in `block (2 levels) in require'
2017-06-12T20:03:52.571484+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.3.0/gems/bundler-1.13.7/lib/bundler/runtime.rb:86:in `each'
2017-06-12T20:03:52.571485+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.3.0/gems/bundler-1.13.7/lib/bundler/runtime.rb:86:in `block in require'
2017-06-12T20:03:52.571485+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.3.0/gems/bundler-1.13.7/lib/bundler/runtime.rb:75:in `each'
2017-06-12T20:03:52.571486+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.3.0/gems/bundler-1.13.7/lib/bundler/runtime.rb:75:in `require'
2017-06-12T20:03:52.571487+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.3.0/gems/bundler-1.13.7/lib/bundler.rb:106:in `require'
2017-06-12T20:03:52.571488+00:00 app[web.1]:   /app/config/application.rb:7:in `<top (required)>'
2017-06-12T20:03:52.571488+00:00 app[web.1]:   /app/config/environment.rb:2:in `require_relative'
2017-06-12T20:03:52.571489+00:00 app[web.1]:   /app/config/environment.rb:2:in `<top (required)>'
2017-06-12T20:03:52.571490+00:00 app[web.1]:   config.ru:3:in `require_relative'
2017-06-12T20:03:52.571491+00:00 app[web.1]:   config.ru:3:in `block in <main>'
2017-06-12T20:03:52.571491+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.3.0/gems/rack-2.0.3/lib/rack/builder.rb:55:in `instance_eval'
2017-06-12T20:03:52.571492+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.3.0/gems/rack-2.0.3/lib/rack/builder.rb:55:in `initialize'
2017-06-12T20:03:52.571493+00:00 app[web.1]:   config.ru:in `new'
2017-06-12T20:03:52.571494+00:00 app[web.1]:   config.ru:in `<main>'
2017-06-12T20:03:52.571494+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.3.0/gems/rack-2.0.3/lib/rack/builder.rb:49:in `eval'
2017-06-12T20:03:52.571495+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.3.0/gems/rack-2.0.3/lib/rack/builder.rb:49:in `new_from_string'
2017-06-12T20:03:52.571496+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.3.0/gems/rack-2.0.3/lib/rack/builder.rb:40:in `parse_file'
2017-06-12T20:03:52.571496+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.3.0/gems/puma-3.9.1/lib/puma/configuration.rb:313:in `load_rackup'
2017-06-12T20:03:52.571497+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.3.0/gems/puma-3.9.1/lib/puma/configuration.rb:242:in `app'
2017-06-12T20:03:52.571498+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.3.0/gems/puma-3.9.1/lib/puma/runner.rb:138:in `load_and_bind'
2017-06-12T20:03:52.571498+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.3.0/gems/puma-3.9.1/lib/puma/single.rb:87:in `run'
2017-06-12T20:03:52.571499+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.3.0/gems/puma-3.9.1/lib/puma/launcher.rb:174:in `run'
2017-06-12T20:03:52.571499+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.3.0/gems/puma-3.9.1/lib/puma/cli.rb:77:in `run'
2017-06-12T20:03:52.571500+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.3.0/gems/puma-3.9.1/bin/puma:10:in `<top (required)>'
2017-06-12T20:03:52.571501+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.3.0/bin/puma:23:in `load'
2017-06-12T20:03:52.571609+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.3.0/bin/puma:23:in `<top (required)>'
```

It looks like the way this gem is loading the SSL lib is wrong.

https://github.com/GemHQ/money-tree/blob/master/lib/openssl_extensions.rb#L9

**Comment by unrealhoang** [comment]
I found out that this happen because of Heroku new stack: `heroku-16`, they don't install libssl-dev for the runtime environment. So either you have to install it yourself using the buidpack, or go back to the old stack `cedar-14`.
https://devcenter.heroku.com/articles/stack-packages

**Comment by guilhermekfe** [comment]
@unrealhoang Thank you! Now it's working.
